version: 2.0

docker_defaults: &docker_defaults
  docker:
    - image: node:lts

procedures:
  yarn_install:
    - checkout
    - run:
        name: Install dependencies
        command: yarn
  git_setup:
    - run:
        name: Git config
        command: git config --global user.email pravin.bashyal@gmail.com && git config --global user.name pravinbashyal
    - add_ssh_keys:
        fingerprints:
          - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"

jobs:
  install:
    <<: *docker_defaults
    steps:
      - procedure: yarn_install
      # - restore_cache: &restore_cache
      #     keys:
      #       - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
      #       - v1-npm-{{checksum ".circleci/config.yml"}}
  # cache:
  #   <<: *docker_defaults
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install dependencies
  #         command: yarn
  #     - save_cache:
  #         key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
  #         paths:
  #           - ~/cli/node_modules
  #           - /usr/local/share/.cache/yarn
  #           - /usr/local/share/.config/yarn
  build:
    <<: *docker_defaults
    # <<: *restore_cache
    steps:
      - checkout:
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: "build"
          command: cd packages/epubinator && yarn build
  prerelease:
    <<: *docker_defaults
    # <<: *restore_cache
    steps:
      - procedure: yarn_install
      - procedure: git_setup
      - run:
          name: Release Canary
          command: cd packages/epubinator && npx lerna version --conventional-commits --conventional-prerelease --preid=alpha --yes
  release:
    <<: *docker_defaults
    steps:
      - procedure: yarn_install
      - procedure: git_setup
      - run:
          name: Release Canary
          command: cd packages/epubinator && npx lerna version --conventional-commits --preid=alpha --yes

workflows:
  version: 2
  "epubinator":
    jobs:
      - install
      # - cache:
      #     requires:
      #       - install
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
      - build:
          requires:
            - install
      - prerelease:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
                - /dependabot-npm_and_yarn-.*/
      - release:
          requires:
            - build
          filters:
            branches:
              only:
               - master

