version: 2.0

docker_defaults: &docker_defaults
  docker:
    - image: node:lts

npm_token: &npm_token
  name: Set .npmrc
  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

yarn_install: &yarn_install
  name: Install dependencies
  command: yarn

yarn_build: &yarn_build
  name: "build"
  command: cd packages/epubinator && yarn build

git_setup: &git_setup
  name: Git config
  command: git config --global user.email pravin.bashyal@gmail.com && git config --global user.name pravinbashyal

ssh_fingerprint: &ssh_fingerprint
  - add_ssh_keys:
      fingerprints:
        - "b7:35:a6:4e:9b:0d:6d:d4:78:1e:9a:97:2a:66:6b:be"

jobs:
  install:
    <<: *docker_defaults
    steps:
      - checkout:
      - run: *yarn_install
  build:
    <<: *docker_defaults
    # <<: *restore_cache
    steps:
      - checkout:
      - run: *yarn_install
      - run: *yarn_build
  prerelease:
    <<: *docker_defaults
    # <<: *restore_cache
    steps:
      - checkout:
      - run: *yarn_install
      - run: *yarn_build
      - run: *git_setup
      - run: *npm_token
      - run:
          name: Release Canary
          command: cd packages/epubinator && yarn release:canary
  release:
    <<: *docker_defaults
    steps:
      - checkout:
      - run: *yarn_install
      - run: *yarn_build
      - run: *git_setup
      - run: *npm_token
      - run:
          name: Release
          command: cd packages/epubinator && yarn release

workflows:
  version: 2
  "epubinator":
    jobs:
      - install
      - build:
          requires:
            - install
      - prerelease:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
                - /dependabot-npm_and_yarn-.*/
      - release:
          requires:
            - build
          filters:
            branches:
              only:
               - master

